export const styles = {
  TableHeaderHeight: {
    height: '70px',
  },
  TableHeaderStyled: {
    width: '48%',
    height: '22px',
    paddingLeft: '150px',
    fontSize: '16px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'left',
    color: '#8c8c8c',
  },
  TableHeaderStyledButtons: {
    width: '10%',
    height: '22px',
    fontSize: '16px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    paddingLeft: '37px',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'left',
    color: '#8c8c8c',
  },
  CellStyle: {
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    paddingLeft: '0',
    paddingRight: '34',
    textAlign: 'center',
    color: '#494949',
    width: '13%',
    paddingTop: '15px',
  },
  ButtonCellStyle: {
    width: '7%',
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    paddingLeft: '0',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'right',
    color: '#494949',
  },
  RowHeight: {
    height: '50px',
  },
};
