export const styles = {
  TableHeaderStyledOne: {
    width: '48%',
    height: '22px',
    fontSize: '16px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    paddingLeft: '4%',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'left',
    color: '#8c8c8c',
  },
  TableHeaderStyled: {
    width: '48%',
    height: '22px',
    fontSize: '16px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'left',
    color: '#8c8c8c',
  },
  TableHeaderHeight: {
    height: '70px',
  },
  TableHeaderStyledButtons: {
    width: '10%',
    height: '22px',
    fontSize: '16px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    paddingLeft: '37px',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'left',
    color: '#8c8c8c',
  },
  TableHeaderStyledTwo: {
    width: '11.5%',
    height: '22px',
    fontSize: '16px',
    fontWeight: 'normal',
    textAlign: 'left',
    color: '#8c8c8c',
  },
  TableHeaderStyledForButton: {
    width: '20%',
    height: '22px',
    textAlign: 'right',
    fontSize: '16px',
    fontWeight: 'normal',
    color: '#8c8c8c',
  },
  ButtonCellStyle: {
    width: '48px',
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    paddingLeft: '0',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'right',
    color: '#494949',
  },
  CellStyleName: {
    height: '22px',
    paddingLeft: '38px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'left',
    color: '#494949',
    width: '13%',
  },
  CellStyleCost: {
    height: '22px',
    paddingLeft: '30px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'left',
    color: '#494949',
    width: '13%',
  },
  CellStyle: {
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    paddingLeft: '2%',
    paddingRight: '34px',
    textAlign: 'left',
    color: '#494949',
    width: '13%',
    paddingTop: '15px',
  },
  CellStyleCredit: {
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'left',
    color: '#494949',
    width: '20%',
  },
  customContentStyle: {
    width: '17%',
    maxWidth: 'none',
  },
  loaderStyled: {
    marginRight: '40px',
    marginTop: '13px',
    marginBottom: '13px',
  },
  checked: {
    background: '#00b74f',
    color: 'white',
    transition: 'all .25s',
    cursor: 'pointer',
  },
  dropDownMenuStyle: {
    float: 'left',
    width: '20%',
    textAlign: 'right',
  },
  dropDownMenuUnderline: {
    display: 'none',
  },
  dropDownMenuLabel: {
    fontFamily: 'Avenir',
    fontSize: '16px',
    fontWeight: '500',
    color: '#00b74f',
  },
  dropDownMenuIcon: {
    fill: '#00b74f',
  },
};
